USE GuildBlog
GO

CREATE LOGIN BlogOwner WITH PASSWORD='testing123'
GO
 
CREATE USER BlogOwner FOR LOGIN GuildBlog
GO

GRANT CONTROL TO BlogOwner
GRANT EXECUTE TO BlogOwner
GRANT CREATE TABLE TO BlogOwner