// <auto-generated />
namespace GuildBlog.UI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class postingdate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(postingdate));
        
        string IMigrationMetadata.Id
        {
            get { return "202004131830394_postingdate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
